# Generated by Django 3.0.5 on 2020-04-17 13:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro_title', models.CharField(blank=True, help_text='Необязательный заголовок H1 на с ранице галерии.', max_length=200, verbose_name='Заголовок блока галереии')),
                ('intro_text', wagtail.core.fields.RichTextField(blank=True, help_text='Необязательное введение после заголовка.', verbose_name='Вводный текст')),
                ('images_per_page', models.IntegerField(default=8, help_text='Как много картинок отображать на странице.', verbose_name='Картинок на страницу')),
                ('collection', models.ForeignKey(help_text='Показывать изображения в галерее из этой коллекции.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Collection', verbose_name='Collection')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
    ]
