# Generated by Django 3.0.5 on 2020-04-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryindex',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='galleryindex',
            name='images_per_page',
        ),
        migrations.RemoveField(
            model_name='galleryindex',
            name='intro_text',
        ),
    ]
