# Generated by Django 3.0.5 on 2020-04-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20200415_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='youtube',
        ),
    ]
