# Generated by Django 3.0.5 on 2020-04-15 17:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_formfield_joinform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinform',
            name='describe_list',
            field=wagtail.core.fields.StreamField([('list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Пункт списка'), icon='list-ul', template='blocks/list_block.html'))]),
        ),
    ]
