# Generated by Django 3.0.5 on 2020-04-15 17:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.core.fields.StreamField([('emphasize', wagtail.core.blocks.CharBlock(icon='title', label='Выделить текст', template='blocks/event_emphasize_block.html')), ('paragraph', wagtail.core.blocks.RichTextBlock(icon='pilcrow', label='Текст', template='blocks/event_paragraph_block.html')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Картинка справа', template='blocks/image_right_block.html')), ('html', wagtail.core.blocks.RawHTMLBlock(icon='code', label='Чистый HTML')), ('list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='Пункт списка'), icon='list-ul', template='blocks/list_block.html')), ('blockquote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(label='Цитата')), ('author', wagtail.core.blocks.CharBlock(label='Автор'))], icon='openquote', template='blocks/quote_block.html'))]),
        ),
    ]
