# Generated by Django 3.0.5 on 2020-04-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_workspacesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspacesettings',
            options={'verbose_name': 'Контакты, время работы'},
        ),
    ]
